[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc_macros = { path = "../macros" }
aoc_tools = { path = "../tools" }
good_lp = "1.14.2"
itertools = "0.14.0"
regex = "1.12.2"
